name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    
    - name: Install dependenciesf
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Train model
      run: |
        python train.py
    
    - name: Run tests
      run: |
        pytest tests/

    - name: Archive model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: model-artifacts
        path: saved_models/ 